flask-boilerplate/api/models/Topics.py
from enum import Enum


class Topics(Enum):
    # __order__ = 'climate_change immigration terrorism socialist students abortion gun_control homelessness unemployment'
    climate_change = ['climate change', 'global warming', 'global climate', 'climate crisis']
    immigration = ['migration', 'transmigration', 'migrant', 'immigrant', 'border control']
    terrorism = ['terrorism', 'terror', 'violence', 'savagery', 'destructive']
    socialist = ['Social Security', 'Medicare', 'health insurance', 'medical insurance', 'healthcare', 'healthcare',
                 'medical']
    students = ['students', 'student loans', 'college', 'study grants', 'scholarship', 'educational grant',
                'fellowship']
    abortion = ['abortion', 'late-term', 'preborn', 'pre-born', 'womb', 'contraception']
    gun_control = ['gun control', 'gun', 'firearms', 'weapons']
    homelessness = ['homeless', 'destitute', 'vagrant', 'poverty', 'begging']
    unemployment = ['unemployed', 'jobless', 'out of work', 'out of a job', 'unemployment', 'no job', 'layoff']

    # topics = ["Climate Change", "Immigration", "Terrorism",
    #          "Social Security and Medicare", "Student Loans", "Abortion",
    #          "Gun Control", "Homelessness", "Unemployment"]

flask-boilerplate/api/views/main.py
import json
from urllib.request import urlopen

import jsonpickle as jsonpickle
from flask import Blueprint, request, render_template, json, Flask

from api.core import create_response, serialize_list, logger
from api.models import db, Person, Candidate, GetData
import random

main = Blueprint("main", __name__, template_folder='templates', static_url_path='/%s',
                 static_folder='static')  # initialize blueprint

data = GetData()

topics_list = ["Technology", "Agricultural", "Economy", "LGBTQ Rights", "Gun Control",
               "Abortion",
               "Student Loan", "Medicare", "Immigration", "Climate Change"]

google_civic_url = 'https://www.googleapis.com/civicinfo/v2/representatives?levels=administrativeArea1' \
                   '&levels=locality&levels=regional&levels=locality&levels=sublocality1&levels=sublocality2' \
                   '&levels=special&levels=country&key' \
                   '=AIzaSyBLqHtNyFSw7PFmorUeUUb8Nwc74bMajc0&address='


# function that is called when you visit /
@main.route("/")
def index():
    return render_template("homepage.html")


@main.route("/faq")
def faq():
    return render_template("faq/faq.homepage.html")


@main.route("/candidates")
def candidates():
    return render_template("candidates/candidates.homepage.html")


@main.route("/candidates-presidential")
def candidates_presidential():
    return render_template("candidates/candidates-presidential.html")


@main.route("/candidates-local")
def candidates_local():
    zip = request.args.get('zip')
    if zip is None:
        msg = "No zip provided."
        logger.info(msg)
        return create_response(status=422, message=msg)

    response = urlopen(google_civic_url + zip)
    array = json.loads(response.read())

    return render_template("candidates/candidates-local.html", data=array)


@main.route("/quiz")
def quiz():
    if request.args.get('id') is None:
        msg = "Please re-complete quiz."
        logger.info(msg)
        return create_response(status=422, message=msg)
    person = Person.query.filter_by(id=request.args.get('id')).first()
    person_data = person.saved_topics

    candidates = Candidate.query.all()

    array = []
    for c in candidates:
        for issues in c.issues:
            for issue_topics in issues.issue_topics:
                array.append({"name": c.name, "issue_name": issues.issue_text, "issue_topics": issue_topics})

    random.shuffle(array)

    return render_template("quiz/quiz.html", array=array)


@main.route("/matches")
def matches(): 
    return render_template("matches.html")

@main.route("/topic")
def topic():
    return render_template("topic.html")


@main.route("/quizhomepage")
def quizhome():
    return render_template("quiz/quizhomepage.html")


@main.route("/api/quiz_topics", methods=["GET"])
def topics():
    return json.dumps(topics_list)


@main.route("/api/save_user", methods=["GET"])
def get_user():
    return render_template("manual/addCustomer.html")


@main.route("/api/save_user", methods=["POST"])
def save_user():
    data = request.form
    if "id" not in data:
        msg = "No id provided for person."
        logger.info(msg)
        return create_response(status=422, message=msg)
    if "topics" not in data:
        msg = "No topics provided for person."
        logger.info(msg)
        return create_response(status=422, message=msg)
    new_person = Person(cookie=data["id"], saved_topics=[json.loads(data["topics"])])

    # commit it to database
    db.session.add_all([new_person])
    db.session.commit()
    return create_response(
        message=f"Successfully created person {new_person.cookie} with id: {new_person.id}"
    )


# function that is called when you visit /persons
@main.route("/api/persons", methods=["GET"])
def get_persons():
    persons = Person.query.all()
    return create_response(data={"persons": serialize_list(persons)})


@main.route("/api/update_candidate", methods=["GET"])
def update_candidate():
    candidate = Candidate.query.filter_by(id=request.args.get('id')).first()
    return render_template("manual/updateCandidate.html", data=candidate)


@main.route("/api/quiz_result", methods=["GET"])
def quiz_result():
    array = request.args.get('array')
    new_person = Person(cookie=0, saved_topics=array)

    # commit it to database
    db.session.add_all([new_person])
    db.session.commit()

    return json.dumps(new_person.id)


@main.route("/api/update_candidate", methods=["POST"])
def update_candidate_post():
    candidate = Candidate.query.filter_by(id=request.args.get('id')).first()

    candidate.id = request.form["id"]
    candidate.name = request.form["name"]
    candidate.website = request.form["website"]
    candidate.issues = json.loads(request.form["issues"])
    candidate.articles = json.loads(request.form["articles"])
    candidate.vote_history = json.loads(request.form["vote_history"])
    candidate.image_link = request.form["image_link"]

    db.session.commit()
    return create_response(
        message=f"Successfully edited person {candidate.name}"
    )


@main.route("/api/make_candidate", methods=["GET"])
def make_them():
    Candidate.test_data(db)
    return 1


@main.route("/api/save_candidate", methods=["GET"])
def get_candidate():
    return render_template("manual/addCandidate.html")


@main.route("/api/save_candidate", methods=["POST"])
def save_candidate():
    data = request.form
    if "name" not in data:
        msg = "No id provided for person."
        logger.info(msg)
        return create_response(status=422, message=msg)

    new_candidate = Candidate(name=data["name"])

    # commit it to database
    db.session.add_all([new_candidate])
    db.session.commit()
    return create_response(
        message=f"Successfully created person {new_candidate.name} with id: {new_candidate.id}"
    )


# function that is called when you visit /persons
@main.route("/api/candidates", methods=["GET"])
def get_candidates():
    candidates = Candidate.query.all()

    if request.args.get('rm') is not None:
        me = Candidate.query.filter_by(id=request.args.get('rm')).first()
        Candidate.query.delete()
        db.session.delete(me)

    response = Flask.response_class(
        response=jsonpickle.encode(candidates),
        status=200,
        mimetype='application/json'
    )
    return response


@main.route("/analyze", methods=["GET"])
def anaylze_data():
    name = request.args.get('name')
    if name is None:
        msg = "No name provided for search."
        logger.info(msg)
        return create_response(status=422, message=msg)
    lines = data.headlines(name)
    output = data.analyze_headline(lines)

    response = Flask.response_class(
        response=jsonpickle.encode(output),
        status=200,
        mimetype='application/json'
    )
    return response

flask-boilerplate/api/views/templates/homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>login</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
    <link href="{{ url_for('.static', filename='css/homepage.css') }}" rel="stylesheet" />
</head>

<body>

   
    <div class='container'>
        <h3 class="text-mid spacer">Welcome to hack-the-vote</h3>
        <div class='outter'>
            <div class='wing'></div>
            <div class='wing'></div>
            <div class='wing'></div>
            <div class='wing'></div>
            <div class='wing'></div>
            <div class='wing'></div>
            <div class='wing'></div>
            <div class='wing'></div>
        </div>
        <div class='outter-two'>
        </div>

        <div class='vote'>
            <h1>VOTE</h1>
        </div>

        <div class='inner'>
            <div class='inner-vote'>
                <div class='flag'><span><em></em> </span></div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="container-fluid topdown">
        <div class="form-group row">
            <div class="col-2"></div>
            <div class="col-8">
                <a href="{{ url_for('main.candidates') }}" id="takeQuiz" class="btn btn-primary btn-block">Go to
                    Candidates</a>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-2"></div>
            <div class="col-8">
                <a href="{{ url_for('main.topic') }}" id="takeQuiz" class="btn btn-primary btn-block">Take Quiz</a>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
    </div>
    <div class="faq">
        <a href="{{ url_for('main.faq') }}">
            <h3 class="">FAQ</h3>
        </a>
    </div>


</body>

</html>

flask-boilerplate/api/views/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Hello World From CS4550 !!!!
</body>
</html>

flask-boilerplate/api/views/templates/matches.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Matches</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="{{ url_for('.static', filename='css/matches.css') }}" rel="stylesheet"/>
</head>

<body>
<h1 class="title-pen"> YOUR MATCHES</h1>

<div class="allprofile">

    <div class="user-profile">
        <img class="avatar"
             src="http://bioguide.congress.gov/bioguide/photo/W/W000817.jpg"
             alt="Ash"/>
        <div class="username">Elizabeth Warren</div>
        <div class="bio">
            United States Senator
        </div>
        <div class="description">
            "Let’s dream big, fight hard,  <br>     and win."
        </div>
        <ul class="data">
            <li>
                <span class="entypo-heart"> 6</span>
            </li>
            <li>
                <span class="entypo-plus"> Donate</span>
            </li>
            <li>
                <span class="entypo-lamp"> More</span>
            </li>
        </ul>
    </div>
    <div class="user-profile">
        <img class="avatar"
             src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Bernie_Sanders_July_2019_retouched.jpg/1920px-Bernie_Sanders_July_2019_retouched.jpg"
             alt="Ash"/>
        <div class="username">Bernie Sanders</div>
        <div class="bio">
            United States Senator
        </div>
        <div class="description">
            "Not me. Us."
        </div>
        <ul class="data">
            <li>
                <span class="entypo-heart"> 4 </span>
            </li>
            <li>
                <span class="entypo-plus"> Donate</span>
            </li>
            <li>
                <span class="entypo-lamp"> More</span>
            </li>
        </ul>
    </div>


    <div class="user-profile">
        <img class="avatar"
             src="https://upload.wikimedia.org/wikipedia/commons/b/bf/Pete_Buttigieg_by_Gage_Skidmore.jpg"
             alt="Ash"/>
        <div class="username">Pete Buttigieg</div>
        <div class="bio">
            Former Mayor of South Bend
        </div>
        <div class="description">
            "It's time for a new generation of American leadership"
        </div>
        <ul class="data">
            <li>
                <span class="entypo-heart"> 3 </span>
            </li>
            <li>
                <span class="entypo-plus"> Donate</span>
            </li>
            <li>
                <span class="entypo-lamp"> More</span>
            </li>
        </ul>
    </div>
</div>
</body>

flask-boilerplate/api/views/templates/topic.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Quiz</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
  <link href="{{url_for('.static', filename='css/topic.css')}}" rel="stylesheet" />
</head>

<body>
  <div>
    <a href="{{ url_for('main.index') }}" class="back-button shawdow animate gery">
      &#8592</a>
  </div>
  <div class="container">
    <div class="demo">
      <div class="demo__content">
        <div class="demo__card-cont">
          <div class="demo__card">
            <div class="demo__card__top_white">
              <div class="demo__card__img10"></div>
              <p class="demo__card__name">Technology</p>
            </div>
            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
          <div class="demo__card">
            <div class="demo__card__top_white">
              <div class="demo__card__img9"></div>
              <p class="demo__card__name">Agricultural</p>
            </div>
            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
          <div class="demo__card">

            <div class="demo__card__top_white">
              <div class="demo__card__img8"></div>
              <p class="demo__card__name">Economy</p>
            </div>

            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
          <div class="demo__card">

            <div class="demo__card__top_white">
              <div class="demo__card__img7"></div>
              <p class="demo__card__name">LGBTQ Rights</p>
            </div>

            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
          <div class="demo__card">

            <div class="demo__card__top_white">
              <div class="demo__card__img6"></div>
              <p class="demo__card__name">Gun Control</p>
            </div>

            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
          <div class="demo__card">

            <div class="demo__card__top_white">
              <div class="demo__card__img5"></div>
              <p class="demo__card__name">Abortion</p>
            </div>

            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
          <div class="demo__card">

            <div class="demo__card__top_white">
              <div class="demo__card__img4"></div>
              <div class="demo__card__name">Student Loan</div>
            </div>

            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
          <div class="demo__card">

            <div class="demo__card__top_white">
              <div class="demo__card__img3"></div>
              <p class="demo__card__name">Medicare</p>
            </div>

            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
          <div class="demo__card">

            <div class="demo__card__top_white">
              <div class="demo__card__img2"></div>
              <p class="demo__card__name ">Immigration</p>
            </div>
            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
          <div class="demo__card">
            <div class="demo__card__top_white">
              <div class="demo__card__img1"></div>
              <p class=" demo__card__name">Climate Change</p>
            </div>

            <div class="demo__card__choice m--reject"></div>
            <div class="demo__card__choice m--like"></div>
            <div class="demo__card__drag"></div>
          </div>
        </div>
      </div>
      <div class=text>
        <div class=t1>Most interested</div<>

          <div class=t2>Less interested</div>
        </div>
        <div class="button_group">

          <button class="action-button shawdow animate mostred">1</button>
          <button class="action-button shawdow animate twored">2</button>
          <button class="action-button shawdow animate threegreen">3</button>
          <button class="action-button shawdow animate fourgreen">4</button>
          <button class="action-button shawdow animate mostgreen">5</button>
        </div>
      </div>
    </div>

  </div>
  </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="{{url_for('.static', filename='js/topic.js')}}"></script>
</body>

</html>