flask-boilerplate/api/models/Candidate.py
from api.core import Mixin
from .base import db
from .data_types.Issue import Issue


# Note that we use sqlite for our tests, so you can't use Postgres Arrays
class Candidate(Mixin, db.Model):
    """Email Table."""

    __tablename__ = "candidate"

    id = db.Column(db.Integer, unique=True, primary_key=True)
    name = db.Column(db.String, nullable=False)
    website = db.Column(db.String)
    issues = db.Column(db.PickleType)
    articles = db.Column(db.PickleType)
    vote_history = db.Column(db.PickleType)
    image_link = db.Column(db.String)

    def __init__(self, name):
        self.name = name

    def make_new(self, website, issues, image_link):
        self.website = website
        self.issues = issues
        self.image_link = image_link

    def __repr__(self):
        return f"<Email {self.email}>"

    topics_list = ["Technology", "Agricultural", "Economy", "LGBTQ Rights", "Gun Control",
                   "Abortion",
                   "Student Loan", "Medicare", "Immigration", "Climate Change"]

    @staticmethod
    def test_data(database):
        candidate1 = Candidate("Donald Trump")
        candidate1.make_new('https://www.donaldjtrump.com/', [
            Issue("Technology", ["Opened up oil and gas production in the U.S.",
                                 "Allocated $50 billion to empower rural America's infrastructure"]),
            Issue("Agricultural", ["Signed the disaster relief bill that provided $19 billion",
                                   "Signed the 2018 Farm Bill which legalized the Production of Industrial Hem"]),
            Issue("Student Loan", ["Implemented the Every Student Succeeds Act (ESSA) to empower states",
                                   "Implemented the year-round distribution of Pell grants"])],
                            "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd"
                            "/Donald_Trump_2013_cropped_more.jpg/220px"
                            "-Donald_Trump_2013_cropped_more.jpg")
        candidate2 = Candidate("Elizabeth Warren")
        candidate2.make_new('https://elizabethwarren.com', [
            Issue("Technology", ["Holding Tech Companies Responsible for the Spread of Disinformation",
                                 "It’s time to break up the biggest tech companies like Amazon, Google, and Facebook"]),
            Issue("Agricultural",
                  ["Guarantee farmers a fair price, reduce overproduction, pay farmers for environmental conservation.",
                   "Ensure Equity for Farmers of Color"]),
            Issue("Student Loan", ["Cancel Student Loan Debt on Day One",
                                   "Quadrupling Title I funding - an additional $450 billion"])],
                            "https://duckduckgo.com/i/8d73105e.jpg")

        candidate3 = Candidate("Bernie Sanders")
        candidate3.make_new('https://berniesanders.com', [
            Issue("Technology", ["Ensure high speed internet for all",
                                 "Break up internet service provider and cable monopolies"]),
            Issue("Agricultural",
                  ["Level the playing field for farmers and farm workers.",
                   "Fundamentally rewrite all of our trade deals to deals to prevent outsourcing "]),
            Issue("Student Loan", ["Guarantee tuition and debt-free public colleges, universities, etc...",
                                   "Invest $1.3 billion every year in private, non-profit historically black colleges"])],
                            "https://duckduckgo.com/i/e8cc1898.jpg")

        candidate3 = Candidate("Joe Biden")
        candidate3.make_new('https://JoeBiden.com', [
            Issue("Technology", ["Install 550,000 charging stations on all new highways ",
                                 "Double amount of spectrum available for wireless broadband"]),
            Issue("Agricultural",
                  ["Revamp trade policy to boost exports, increasing investment in renewable energy and rural broadband",
                   "Protect small and medium-sized farmers and producers by strengthening enforcement of antitrust"]),
            Issue("Student Loan", ["After 20 years of student loan repayment, your federal student loans are forgiven",
                                   "Allow borrowers to discharge their student loans in bankruptcy."])],
                            "https://duckduckgo.com/i/e8cc1898.jpg")

        candidate4 = Candidate("Pete Buttigieg")
        candidate4.make_new('https://www.peteforamerica.com/', [
            Issue("Technology", ["Install 550,000 charging stations on all new highways ",
                                 "Double amount of spectrum available for wireless broadband"]),
            Issue("Agricultural",
                  ["Revamp trade policy to boost exports, increasing investment in renewable energy and rural broadband",
                   "Protect small and medium-sized farmers and producers by strengthening enforcement of antitrust"]),
            Issue("Student Loan", ["After 20 years of student loan repayment, your federal student loans are forgiven",
                                   "Allow borrowers to discharge their student loans in bankruptcy."])],
                            "https://duckduckgo.com/i/1663508a.jpg")

        candidate5 = Candidate("Michael Bloomberg")
        candidate5.make_new('https://MikeBloomberg.com', [
            Issue("Technology", ["Install 550,000 charging stations on all new highways ",
                                 "Double amount of spectrum available for wireless broadband"]),
            Issue("Agricultural",
                  [
                      "Revamp trade policy to boost exports, increasing investment in renewable energy and rural broadband",
                      "Protect small and medium-sized farmers and producers by strengthening enforcement of antitrust"]),
            Issue("Student Loan", ["After 20 years of student loan repayment, your federal student loans are forgiven",
                                   "Allow borrowers to discharge their student loans in bankruptcy."])],
                            "https://duckduckgo.com/i/e8984e57.jpg")

        database.session.add_all([candidate1, candidate2, candidate3, candidate4, candidate5])
        database.session.commit()

flask-boilerplate/api/views/main.py
import json
from urllib.request import urlopen

import jsonpickle as jsonpickle
from flask import Blueprint, request, render_template, json, Flask

from api.core import create_response, serialize_list, logger
from api.models import db, Person, Candidate, GetData
import random

main = Blueprint("main", __name__, template_folder='templates', static_url_path='/%s',
                 static_folder='static')  # initialize blueprint

data = GetData()

topics_list = ["Technology", "Agricultural", "Economy", "LGBTQ Rights", "Gun Control",
               "Abortion",
               "Student Loan", "Medicare", "Immigration", "Climate Change"]

google_civic_url = 'https://www.googleapis.com/civicinfo/v2/representatives?levels=administrativeArea1' \
                   '&levels=locality&levels=regional&levels=locality&levels=sublocality1&levels=sublocality2' \
                   '&levels=special&levels=country&key' \
                   '=AIzaSyBLqHtNyFSw7PFmorUeUUb8Nwc74bMajc0&address='


# function that is called when you visit /
@main.route("/")
def index():
    return render_template("homepage.html")


@main.route("/faq")
def faq():
    return render_template("faq/faq.homepage.html")


@main.route("/candidates")
def candidates():
    return render_template("candidates/candidates.homepage.html")


@main.route("/candidates-presidential")
def candidates_presidential():
    return render_template("candidates/candidates-presidential.html")


@main.route("/candidates-local")
def candidates_local():
    zip = request.args.get('zip')
    if zip is None:
        msg = "No zip provided."
        logger.info(msg)
        return create_response(status=422, message=msg)

    response = urlopen(google_civic_url + zip)
    array = json.loads(response.read())

    return render_template("candidates/candidates-local.html", data=array)


@main.route("/quiz")
def quiz():
    if request.args.get('id') is None:
        msg = "Please re-complete quiz."
        logger.info(msg)
        return create_response(status=422, message=msg)
    person = Person.query.filter_by(id=request.args.get('id')).first()
    person_data = person.saved_topics

    candidates = Candidate.query.all()

    array = []
    for c in candidates:
        for issues in c.issues:
            for issue_topics in issues.issue_topics:
                array.append({"name": c.name, "issue_name": issues.issue_text, "issue_topics": issue_topics})

    random.shuffle(array)

    return render_template("quiz/quiz.html", array=array)


@main.route("/matches")
def matches(): 
    return render_template("matches.html")

@main.route("/topic")
def topic():
    return render_template("topic.html")


@main.route("/quizhomepage")
def quizhome():
    return render_template("quiz/quizhomepage.html")


@main.route("/api/quiz_topics", methods=["GET"])
def topics():
    return json.dumps(topics_list)


@main.route("/api/save_user", methods=["GET"])
def get_user():
    return render_template("manual/addCustomer.html")


@main.route("/api/save_user", methods=["POST"])
def save_user():
    data = request.form
    if "id" not in data:
        msg = "No id provided for person."
        logger.info(msg)
        return create_response(status=422, message=msg)
    if "topics" not in data:
        msg = "No topics provided for person."
        logger.info(msg)
        return create_response(status=422, message=msg)
    new_person = Person(cookie=data["id"], saved_topics=[json.loads(data["topics"])])

    # commit it to database
    db.session.add_all([new_person])
    db.session.commit()
    return create_response(
        message=f"Successfully created person {new_person.cookie} with id: {new_person.id}"
    )


# function that is called when you visit /persons
@main.route("/api/persons", methods=["GET"])
def get_persons():
    persons = Person.query.all()
    return create_response(data={"persons": serialize_list(persons)})


@main.route("/api/update_candidate", methods=["GET"])
def update_candidate():
    candidate = Candidate.query.filter_by(id=request.args.get('id')).first()
    return render_template("manual/updateCandidate.html", data=candidate)


@main.route("/api/quiz_result", methods=["GET"])
def quiz_result():
    array = request.args.get('array')
    new_person = Person(cookie=0, saved_topics=array)

    # commit it to database
    db.session.add_all([new_person])
    db.session.commit()

    return json.dumps(new_person.id)


@main.route("/api/update_candidate", methods=["POST"])
def update_candidate_post():
    candidate = Candidate.query.filter_by(id=request.args.get('id')).first()

    candidate.id = request.form["id"]
    candidate.name = request.form["name"]
    candidate.website = request.form["website"]
    candidate.issues = json.loads(request.form["issues"])
    candidate.articles = json.loads(request.form["articles"])
    candidate.vote_history = json.loads(request.form["vote_history"])
    candidate.image_link = request.form["image_link"]

    db.session.commit()
    return create_response(
        message=f"Successfully edited person {candidate.name}"
    )


@main.route("/api/make_candidate", methods=["GET"])
def make_them():
    Candidate.test_data(db)
    return 1


@main.route("/api/save_candidate", methods=["GET"])
def get_candidate():
    return render_template("manual/addCandidate.html")


@main.route("/api/save_candidate", methods=["POST"])
def save_candidate():
    data = request.form
    if "name" not in data:
        msg = "No id provided for person."
        logger.info(msg)
        return create_response(status=422, message=msg)

    new_candidate = Candidate(name=data["name"])

    # commit it to database
    db.session.add_all([new_candidate])
    db.session.commit()
    return create_response(
        message=f"Successfully created person {new_candidate.name} with id: {new_candidate.id}"
    )


# function that is called when you visit /persons
@main.route("/api/candidates", methods=["GET"])
def get_candidates():
    candidates = Candidate.query.all()

    if request.args.get('rm') is not None:
        me = Candidate.query.filter_by(id=request.args.get('rm')).first()
        Candidate.query.delete()
        db.session.delete(me)

    response = Flask.response_class(
        response=jsonpickle.encode(candidates),
        status=200,
        mimetype='application/json'
    )
    return response


@main.route("/analyze", methods=["GET"])
def anaylze_data():
    name = request.args.get('name')
    if name is None:
        msg = "No name provided for search."
        logger.info(msg)
        return create_response(status=422, message=msg)
    lines = data.headlines(name)
    output = data.analyze_headline(lines)

    response = Flask.response_class(
        response=jsonpickle.encode(output),
        status=200,
        mimetype='application/json'
    )
    return response

flask-boilerplate/api/views/templates/candidates/candidate_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

flask-boilerplate/api/views/templates/candidates/candidates-local.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Profile</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="{{ url_for('.static', filename='css/candidates-local.css') }}" rel="stylesheet"/>
</head>

<body>
<div class="container-fluid">
    <div class="form-group row">
            <div class="col-2">
                <a href="{{ url_for('main.index') }}" class="btn back-button shadow animate gery">
                    &#8592</a>
            </div>
            <div class="col-10">
            </div>
        </div>
    <div>

        <div class="topdown text-mid">
            <h3> Find your representatives!</h3>
            <div class="form-group row">
                {% for item in data["officials"] %}
                    <div class="card col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
                        <div class="card">
                            <img style="max-height: 300px; max-width: 150px; align-self: center;" src="{{ item["photoUrl"] |default("") }} "
                                 class="card-img-top" alt="">
                            <div class="card-body">
                                <h5 class="card-title"> {{ item["name"] |default("") }}</h5>
                                <p class="card-text">{{ item["issues"] |default("") }}</p>
                                {% if "urls" in item %}
                                    <a href="{{ item["urls"][0]|default("") }}" class="btn btn-primary">Website</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>
    <div class="form-group row">
        <div class="col-12">
            <a href="{{ url_for('main.faq') }}">
                <h3 class="text-mid">FAQ</h3>
            </a>
        </div>
    </div>
</div>

</body>

</html>

flask-boilerplate/api/views/templates/candidates/candidates-presidential.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profile</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
  <link href="{{ url_for('.static', filename='css/candidates.css') }}" rel="stylesheet" />
  <script src="{{ url_for('.static', filename='js/presidential.js') }}"></script>
</head>

<body>
  <div class="container-fluid">
    <div class="title-loc text-mid spacer">
      <h3> Presidential Candidates! </h3>
      <div class="container-fluid">
        <div class="row" id="cards">
        </div>
      </div>
        
        <div class="form-group row">
          <div class="col-12">
            <a href="{{ url_for('main.faq') }}">
              <h3 class="text-mid">FAQ</h3>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-2">
        <a href="{{url_for('main.index')}}" class="btn back-button shadow animate gery">
          &#8592</a>
      </div>
      <div class="col-10">
      </div>
    </div>
  </div>

</body>

</html>

flask-boilerplate/api/views/templates/candidates/candidates.homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Profile</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="{{ url_for('.static', filename='css/candidates.css') }}" rel="stylesheet"/>
</head>

<body>
<div class="container-fluid">
    <div class="topdown text-mid">
        <h3> Find your candidate!</h3>
        <div class="form-group row">
            <label for="Zipcode" class="col-2 col-form-label zippy">
                Zipcode: </label>
            <div class="col-8">
                <input class="form-control" id="Zipcode" placeholder="05403">
            </div>
            <div class="col-2">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2"></div>
            <div class="col-8">
                <a href="{{ url_for('main.candidates_local') }}" id="next-step-1"
                   class="btn btn-success btn-block">Find Local Representatives</a>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="form-group row">
            <div class="col-2"></div>
            <div class="col-8">
                <a href="{{ url_for('main.candidates_presidential') }}" id="next-step-2"
                   class="btn btn-primary btn-block">Presidential Candidates</a>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <a href="{{ url_for('main.index') }}" class="btn back-button shadow animate gery">
                &#8592</a>
        </div>
        <div class="col-10">
        </div>
    </div>

    <div class="form-group row">
        <div class="col-12 faq">
            <a href="{{ url_for('main.faq') }}">
                <h3 class="text-mid">FAQ</h3>
            </a>
        </div>
    </div>
</div>
<script src="{{ url_for('.static', filename='js/location.js') }}"></script>
</body>

</html>